### ISSUE TITLE
VSCode extension intellisense doesn't seem to work (no auto-complete, hovertext, etc.)

### ISSUE THREAD

**Issue by svioletg** [bscotch/stitch#105] opened 2023-06-23 04:40 UTC
I'm on v0.29.2. No matter what file, intellisense for `.gml` files doesn't seem to work at all for me, no auto-complete or hovertext even for built-in standard functions like `instance_create_layer()`. I attached a couple photos and a GIF to show this.

Syntax highlighting seems to work just fine, but that's about it - as mentioned in another issue, the Stitch: Resources tab in the sidebar opens up to a blank window, as well. The extension description says something about a Stitch config, but I can't seem to find where the "default" config is, or what would go into one if I were to create it myself.

Edit for clarification: auto-complete works for variables, functions, and statements already used in the file that's open, but nothing outside of that. `place_meeting()` and `if` will auto-complete, but `switch` won't, for example. Plus, although `place_meeting` will auto-complete since it is already present in the file, VSCode doesn't seem to recognize it as a function, as it doesn't add parenthesis after hitting enter to complete it.

![image](https://github.com/bscotch/stitch/assets/16344364/61566b41-92c2-4ffa-91b3-6bf4fa30384b)
![image](https://github.com/bscotch/stitch/assets/16344364/da106fc9-51fd-434d-a860-c195ff7689f2)
![Code_2023-06-22_23-39-55](https://github.com/bscotch/stitch/assets/16344364/820ad8ba-7cf4-47cc-893e-f370cce86535)

**Comment by adam-coster** [comment] 2023-06-23 16:02
You are correct that this is a duplicate of #83, so I'll close this issue in favor of that one. Thanks for the report!

**Closed as completed by adam-coster** 2023-06-23 16:02 UTC
