### ISSUE TITLE
"Undeclared symbol" error on struct members not in the same file they've were declared in

### ISSUE THREAD

**Issue by svioletg** [bscotch/stitch#111] opened 2023-07-12 18:08 UTC
In `obj_player/Create_0.gml`, there's a struct defined as such:
```
// Sprite index
sprdex = {
	idle: spr_jackieplat_idle,
	walk: spr_jackieplat_walk,
	run: spr_jackieplat_run
}
```
And the line `sprite_index = sprdex.idle;` right after, which the extension has no problem with. However, in the Step event:
```
if moving
{
	// TODO: Animate here
	sprite_index = sprdex.idle;
}
else
{ sprite_index = sprdex.idle; }
```
`idle` is not recognized as a member of the `sprdex` struct:
![image](https://github.com/bscotch/stitch/assets/16344364/5008288f-b53e-43a0-b3c8-de33dbf13b2c)

The error seems to go away if I type anything into the file, but it then comes *back* if I type into any other file:
![Code_2023-07-12_12-44-29](https://github.com/bscotch/stitch/assets/16344364/edf35ef6-4f4d-4d60-9b4d-9e33ec2e03a2)

**Comment by adam-coster** [comment] 2023-07-12 22:15
It looks like the editor knows what the variable is since you get hovertext, but are getting spurious errors for some reason. I have it set up to reprocess files when you focus them, which causes some cascading diagnostic recomputation for files that reference stuff from the newly-focused one. Probably there's an order-of-ops problem of some sort I'll have to investigate.

**Comment by adam-coster** [comment] 2023-07-13 21:17
Thanks to this very thorough report I was able to track down the issue. It should be resolved in the latest version (1.8.2).

**Closed as completed by adam-coster** 2023-07-13 21:17 UTC

**Comment by kyleshrader** [comment] 2024-06-10 16:19
Looks like this may still be an issue?

![image](https://github.com/bscotch/stitch/assets/5632571/30c3b073-18cc-4b61-9bbe-d1652fd0dc20)

I am new to GameMaker though, so I'm curious if this is even the right way to do this. But in GML it seems to be working fine. Just not in VSCode

Edit: I restarted vscode and that fixed the issue. Is there an easier way to resolve this than restarting?

**Comment by adam-coster** [comment] 2024-06-10 17:00
@kyleshrader It's very weird that the hovertext is showing you simultaneously that it's an "undeclared symbol" and that it has type `Id.Instance`, so Stitch is definitely doing something wrong.

Any chance you have a *global* variable called `player`? If so, there's some ambiguity here that Stitch might not be handling properly -- make sure your globals don't have names that conflict with instance/local variables (naming globals with ALL_CAPS is a common practice to help with that).

If that's not what's going on, I'll need some more info about how to replicate the issue.

My understanding of what you're seeing is: when you create a struct literal as an instance variable in a create event, Stitch doesn't know about that variable when you go to reference it in the step event until you restart VSCode. But after you've restarted, Stitch *does* know about the variable from then on out.

Presumably, this then becomes a non-issue for that variable, but the annoyance is that each time you want to do something similar (create an instance variable and then reference it somewhere) you have to reload VSCode again for Stitch to now recognize *that* variable.

Is that all correct?

Additional questions:

- Does this happen for every new instance variable you create, or did this just happen once?
- Does it happen when you add an instance variable to an object that already existed in your current session?
- Does it happen when you add an instance variable to an object that was *newly created* in your current session?
- When it happens, if you hover over the variable in the Create event does it show up as expected? In other words, does it look like Stitch knows about the variable in the Create event but not in the Step, or does it not know about them in both?
- When it happens, if you make a small edit (e.g. add a space somewhere) and re-save, either the Create event or the Step event, does that resolve it? (That would cause Stitch to re-process the files and hopefully fix the issue, rather than having to restart VSCode.)

And if there's any other info you can provide that might help me reproduce the problem, please add it 😀

**Comment by kyleshrader** [comment] 2024-06-11 07:10
I do not have any global variables named player.
Your understanding is correct. And yes, once it was resolved, the references to the variable no longer had an issue.

This just happened once and I haven't been able to reproduce it.
I tried both of these scenarios and had no luck reproducing, among other scenarios I could think of.

If it happens again, I will make sure to come with more information.

---

If anyone else encounters this issue, pressing `ctrl + shift + p` and performing `Developer: Reload Window` or restarting VS Code is likely to resolve the issue. :)
