### ISSUE TITLE
undeclared variable in for loops

### ISSUE THREAD

**Issue by kxjjuneau** [bscotch/stitch#246] opened 2024-07-12 19:32 UTC
for(i = 0; i < listSize; i++) 

this line says i is undeclared at **i** < listSize
which seems wrong if gml allows me to use i in the loop itself

changing to this removes the error msg so its not that big of a deal just thought id document it since the first way I did it is technically allowed
for(var i = 0; i < listSize; i++)

**Comment by adam-coster** [comment] 2024-07-15 21:40
Stitch is a little less loose than GameMaker. Technically the explicit `var` is the correct choice -- without it the `i` will be expected to either be an instance variable or a global, so it's easy to get into trouble even if GameMaker technically allows it.

Closing as intended.

**Closed as completed by adam-coster** 2024-07-15 21:40 UTC
